var JSON=JSON||{};
JSON.parse=JSON.parse||function(){function m(l,j,a){return j?r[j]:String.fromCharCode(parseInt(a,16))}var s=new RegExp('(?:false|true|null|[\\{\\}\\[\\]]|(?:-?\\b(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?\\b)|(?:"(?:[^\\0-\\x08\\x0a-\\x1f"\\\\]|\\\\(?:["/\\\\bfnrt]|u[0-9A-Fa-f]{4}))*"))',"g"),o=new RegExp("\\\\(?:([^u])|u(.{4}))","g"),r={'"':'"',"/":"/","\\":"\\",b:"\u0008",f:"\u000c",n:"\n",r:"\r",t:"\t"},h=new String(""),p=Object.hasOwnProperty;return function(l,j){l=l.match(s);var a,b=
l[0],f=false;if("{"===b)a={};else if("["===b)a=[];else{a=[];f=true}for(var c,g=[a],i=1-f,d=l.length;i<d;++i){b=l[i];var e;switch(b.charCodeAt(0)){default:e=g[0];e[c||e.length]=+b;c=void 0;break;case 34:b=b.substring(1,b.length-1);if(b.indexOf("\\")!==-1)b=b.replace(o,m);e=g[0];if(!c)if(e instanceof Array)c=e.length;else{c=b||h;break}e[c]=b;c=void 0;break;case 91:e=g[0];g.unshift(e[c||e.length]=[]);c=void 0;break;case 93:g.shift();break;case 102:e=g[0];e[c||e.length]=false;c=void 0;break;case 110:e=
g[0];e[c||e.length]=null;c=void 0;break;case 116:e=g[0];e[c||e.length]=true;c=void 0;break;case 123:e=g[0];g.unshift(e[c||e.length]={});c=void 0;break;case 125:g.shift();break}}if(f){if(g.length!==1)throw new Error;a=a[0]}else if(g.length)throw new Error;if(j){var v=function(t,u){var k=t[u];if(k&&typeof k==="object"){var q=null;for(var n in k)if(p.call(k,n)&&k!==t){var w=v(k,n);if(w!==void 0)k[n]=w;else{q||(q=[]);q.push(n)}}if(q)for(n=q.length;--n>=0;)delete k[q[n]]}return j.call(t,u,k)};a=v({"":a},
"")}return a}}();
(function(){function m(a){return a<10?"0"+a:a}function s(a){r.lastIndex=0;return r.test(a)?'"'+a.replace(r,function(b){var f=l[b];return typeof f==="string"?f:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function o(a,b){var f,c,g=h,i,d=b[a];if(d&&typeof d==="object"&&typeof d.toJSON==="function")d=d.toJSON(a);if(typeof j==="function")d=j.call(b,a,d);switch(typeof d){case "string":return s(d);case "number":return isFinite(d)?String(d):"null";case "boolean":case "null":return String(d);case "object":if(!d)return"null";
h+=p;i=[];if(Object.prototype.toString.apply(d)==="[object Array]"){c=d.length;for(a=0;a<c;a+=1)i[a]=o(a,d)||"null";b=i.length===0?"[]":h?"[\n"+h+i.join(",\n"+h)+"\n"+g+"]":"["+i.join(",")+"]";h=g;return b}if(j&&typeof j==="object"){c=j.length;for(a=0;a<c;a+=1){f=j[a];if(typeof f==="string")if(b=o(f,d))i.push(s(f)+(h?": ":":")+b)}}else for(f in d)if(Object.hasOwnProperty.call(d,f))if(b=o(f,d))i.push(s(f)+(h?": ":":")+b);b=i.length===0?"{}":h?"{\n"+h+i.join(",\n"+h)+"\n"+g+"}":"{"+i.join(",")+"}";
h=g;return b}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+m(this.getUTCMonth()+1)+"-"+m(this.getUTCDate())+"T"+m(this.getUTCHours())+":"+m(this.getUTCMinutes())+":"+m(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var r=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h,p,l={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,b,f){var c;p=h="";if(typeof f==="number")for(c=0;c<f;c+=1)p+=" ";else if(typeof f==="string")p=f;if((j=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw new Error("JSON.stringify");return o("",{"":a})}})();
